name: deustocine

on:
  push:
     branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'   
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
    - name: create database in mysql-server
      run: mysql -uroot -h127.0.0.1 < src/sql/deustocinedb.sql  
    - name: compile the code
      run: mvn clean compile
    - name: Test with Maven
      run: mvn test -Punit
    - name: Datanucleus enhance
      run: mvn datanucleus:enhance
    - name: Create Datanucleus schema
      run: mvn datanucleus:schema-create
    - name: Launch the server in background mode 
      run: mvn jetty:run &
    - name: Sleep for 10 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'
    - name: Data
      run: mvn exec:java -Pdatos
    - name: Run Integration Test
      run: mvn test -Pintegration
    - name: Install doxygen
      run: sudo apt-get install -y doxygen
    - name: Install graphviz
      run: sudo apt-get install -y graphviz
    - name: Generate documentation
      run: mvn doxygen:report
    - name: Publish on Github Pages
      uses: crazy-max/ghaction-github-pages@v2.3.0
      with:
        build_dir: target/doxygen/html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}